import type { Meal } from './types'

// Recipes from 'BTC 2026' by Coached by Vicks. Per-serving macros.
export const SEED_MEALS_LIB: Meal[] = [
  {
    id: 'btc-peanut-butter-banana-overnight-oats',
    name: 'Peanut Butter Banana Overnight Oats',
    section: 'breakfast',
    kcal: 596.0, p: 26.8, c: 76.2, f: 21.0, fibre: 12.4,
    ingredients: ['60 g oats', '200 ml low fat milk', '100 g ripe banana (approximately 1 medium banana)', '20 g smooth peanut butter (1 heaped tablespoon)', '10 g chia seeds (2 teaspoons)', '100 g plain greek yoghurt', '5 g honey (1 teaspoon) (optional, depending on banana sweetness)', '2 g cinnamon (½ teaspoon)', '1 g vanilla extract (¼ teaspoon)'],
    method: ['Add rolled oats, chia seeds, cinnamon, and vanilla extract to a sealable jar or container.', 'Pour in the milk and stir well to ensure the chia seeds are evenly distributed.', 'Add the greek yoghurt and mix until combined.', 'Slice the banana and fold half into the oat mixture.', 'Cover and refrigerate overnight (minimum 6 hours).', 'Before serving, top with the remaining banana slices and drizzle with peanut butter.'],
    source: 'Coached by Vicks — BTC 2026',
  },
  {
    id: 'btc-muesli-yoghurt',
    name: 'Muesli & Yoghurt',
    section: 'breakfast',
    kcal: 470.0, p: 15.5, c: 72.0, f: 12.8, fibre: 8.5,
    ingredients: ['200 g NutriDay Strawberry Low Fat Yoghurt', '50 g Jungle Lite Mixed Berries Muesli', '100 g fresh strawberries, sliced', '80 g banana, sliced', '10 g ground flax seeds'],
    method: ['Add the strawberry yoghurt to a bowl.', 'Sprinkle the Jungle Lite Mixed Berries Muesli over the yoghurt.', 'Add sliced strawberries and banana.', 'Sprinkle over the ground flax seeds.', 'Serve immediately.'],
    source: 'Coached by Vicks — BTC 2026',
  },
  {
    id: 'btc-classic-warm-weet-bix-with-butter-milk-b',
    name: 'Classic Warm Weet-Bix with Butter, Milk & Brown Sugar',
    section: 'breakfast',
    kcal: 419.0, p: 15.0, c: 59.5, f: 15.2, fibre: 7.5,
    ingredients: ['3 × Weet-Bix Original biscuits (51 g)', '250 ml full cream milk', '10 g butter', '15 g brown sugar', '2 g cinnamon (½ teaspoon) (optional)'],
    method: ['Warm the milk in a saucepan or microwave until hot but not boiling.', 'Place the 3 Weet-Bix biscuits in a bowl.', 'Pour the warm milk over the Weet-Bix and allow it to soften for 30– 60 seconds.', 'Add the butter and stir until melted and creamy.', 'Sprinkle over the brown sugar and cinnamon.', 'Stir and serve immediately.'],
    source: 'Coached by Vicks — BTC 2026',
  },
  {
    id: 'btc-avocado-egg-on-toast',
    name: 'Avocado & Egg on Toast',
    section: 'breakfast',
    kcal: 484.0, p: 24.5, c: 39.8, f: 27.2, fibre: 11.2,
    ingredients: ['2 slices wholewheat bread', '2 large free-range eggs', '½ medium avocado (70 g flesh)', '50 g cherry tomatoes, halved', '30 g baby spinach', '5 ml lemon juice (1 teaspoon)', '1 g chilli flakes (optional)', '1 g black pepper', '1 g salt (adjust to taste)'],
    method: ['Toast the bread until golden and crisp.', 'Cook eggs in a non-stick pan without added oil (or use a light spray if needed).', 'Mash avocado with lemon juice, salt, pepper, and chilli flakes.', 'Spread avocado over the toast.', 'Add baby spinach and cherry tomatoes.', 'Top with cooked eggs.', 'Season and serve immediately.'],
    source: 'Coached by Vicks — BTC 2026',
  },
  {
    id: 'btc-salted-caramel-protein-smoothie',
    name: 'Salted Caramel Protein Smoothie',
    section: 'breakfast',
    kcal: 405.0, p: 42.0, c: 48.0, f: 8.0, fibre: 6.0,
    ingredients: ['30 g whey protein powder (vanilla)', '100 g fat-free plain yoghurt', '1 medium banana (100 g peeled)', '1 Medjool date (20 g, pitted)', '10 g almond butter', '5 g ground flax seeds', '1 g sea salt (small crack of salt)', '100 g ice cubes', '2–3 drops vanilla extract (optional)'],
    method: ['Remove the pit from the Medjool date.', 'Add fat-free yoghurt, banana, whey protein powder, date, almond butter, flax seeds, salt, vanilla extract, and ice to a blender.', 'Blend for 45–60 seconds until smooth and creamy.', 'Taste and adjust salt slightly to achieve the salted caramel flavour.', 'Serve immediately.'],
    source: 'Coached by Vicks — BTC 2026',
  },
  {
    id: 'btc-toasted-cheese-tomato-sandwich',
    name: 'Toasted Cheese & Tomato Sandwich',
    section: 'breakfast',
    kcal: 430.0, p: 36.0, c: 42.0, f: 13.0, fibre: 6.0,
    ingredients: ['2 slices wholewheat bread (70 g)', '100 g fat-free cottage cheese', '30 g cheddar cheese, grated', '60 g tomato, thinly sliced', '10 g onion, thinly sliced (optional)', '2 g garlic powder (½ teaspoon)', '1 g dried mixed herbs', '1 g black pepper', '1 g salt (adjust to taste)'],
    method: ['Preheat a sandwich press or non-stick pan.', 'Mix fat-free cottage cheese with garlic powder, mixed herbs, salt, and pepper.', 'Spread the cottage cheese mixture evenly onto one slice of bread.', 'Add grated cheddar cheese, sliced tomato, and onion.', 'Place the second slice of bread on top.', 'Lightly spray the outside of the bread with Spray and Cook.', 'Toast for 3–5 minutes until golden brown and the cheddar has melted.', 'Slice and serve warm.'],
    source: 'Coached by Vicks — BTC 2026',
  },
  {
    id: 'btc-classic-chicken-mayo-wrap',
    name: 'Classic Chicken Mayo Wrap',
    section: 'lunch',
    kcal: 500.0, p: 48.0, c: 48.0, f: 12.0, fibre: 9.0,
    ingredients: ['120 g cooked skinless chicken breast (approximately 160 g raw chicken breast before', 'cooking)', '1 large wholewheat tortilla wrap (60 g)', '40 g fat-free cottage cheese', '15 g light mayonnaise', '50 g lettuce, shredded', '50 g cucumber, sliced', '50 g tomato, diced', '20 g red onion, finely sliced', '10 g gherkins, chopped (optional)', '5 g lemon juice', '2 g garlic powder', '2 g smoked paprika', '1 g black pepper', '1 g salt', 'Spray and Cook'],
    method: ['Season cooked chicken (or season raw chicken before cooking) with garlic powder, smoked paprika, salt, and pepper.', 'Cook chicken until fully cooked, then allow to rest before weighing 120 g cooked chicken.', 'Slice chicken into thin strips.', 'Mix fat-free cottage cheese, light mayonnaise, and lemon juice together.', 'Warm tortilla wrap for 20–30 seconds.', 'Spread cottage cheese mayo mixture onto the wrap.', 'Add lettuce, cucumber, tomato, onion, gherkins, and chicken.', 'Fold tightly and serve.'],
    source: 'Coached by Vicks — BTC 2026',
  },
  {
    id: 'btc-tuna-sweetcorn-sandwich',
    name: 'Tuna Sweetcorn Sandwich',
    section: 'lunch',
    kcal: 450.0, p: 43.0, c: 43.0, f: 11.0, fibre: 7.0,
    ingredients: ['1 can tuna in brine, drained (120 g drained weight)', '2 slices wholewheat bread (70 g)', '50 g fat-free cottage cheese', '15 g light mayonnaise', '50 g sweetcorn, drained', '30 g cucumber, finely diced', '30 g tomato, sliced', '15 g red onion, finely diced', '10 g gherkins, chopped (optional)', '5 g lemon juice', '2 g garlic powder', '1 g black pepper', '1 g salt', '10 g lettuce leaves'],
    method: [],
    source: 'Coached by Vicks — BTC 2026',
  },
  {
    id: 'btc-simple-mince-rice',
    name: 'Simple Mince & Rice',
    section: 'lunch',
    kcal: 585.0, p: 45.0, c: 62.0, f: 17.0, fibre: 9.0,
    ingredients: ['150 g cooked lean beef mince (5% fat) (approximately 200 g raw mince before', 'cooking)', '150 g cooked basmati rice (approximately 50 g dry rice)', '100 g mixed vegetables (carrots, peas, corn)', '50 g baby spinach', '50 g onion, diced', '100 g tomato, chopped', '15 g tomato paste', '5 g Worcestershire sauce', '2 g smoked paprika', '2 g garlic powder', '1 g cumin', '1 g black pepper', '1 g salt', 'Spray and Cook'],
    method: ['Heat a non-stick pan and lightly spray with Spray and Cook.', 'Add diced onion and cook for 2–3 minutes until softened.', 'Add cooked beef mince and season with smoked paprika, garlic powder, cumin, salt, and pepper.', 'Stir through tomato paste, chopped tomato, and Worcestershire sauce.', 'Simmer for 5–8 minutes until the flavours combine.', 'Add spinach and allow it to wilt.', 'Serve the mince over the cooked rice.', 'Add mixed vegetables on the side or stir them through the mince.'],
    source: 'Coached by Vicks — BTC 2026',
  },
  {
    id: 'btc-chicken-pesto-pasta',
    name: 'Chicken Pesto Pasta',
    section: 'lunch',
    kcal: 590.0, p: 55.0, c: 63.0, f: 16.0, fibre: 7.0,
    ingredients: ['140 g cooked skinless chicken breast (approximately 190 g raw chicken', 'breast)', '180 g cooked pasta (approximately 60 g dry pasta)', '25 g basil pesto', '50 g fat-free cottage cheese', '50 ml low-fat milk', '80 g baby spinach', '100 g cherry tomatoes', '10 g parmesan cheese', 'Seasonings'],
    method: ['Cook pasta according to packet instructions until al dente.', 'Measure 180 g cooked pasta and set aside.', 'Season chicken breast with garlic powder, salt, and pepper.', 'Lightly spray a non-stick pan with Spray and Cook.', 'Cook chicken until golden and fully cooked, then allow to rest and slice.', 'In a bowl, mix pesto, fat-free cottage cheese, and milk to create a creamy sauce.', 'Add pasta, sauce, spinach, and cherry tomatoes to the pan.', 'Heat gently for 2–3 minutes until spinach wilts and sauce coats the pasta.', 'Add sliced chicken and finish with parmesan.', 'Serve warm.'],
    source: 'Coached by Vicks — BTC 2026',
  },
  {
    id: 'btc-greek-chicken-salad-bowl',
    name: 'Greek Chicken Salad Bowl',
    section: 'lunch',
    kcal: 560.0, p: 55.0, c: 48.0, f: 18.0, fibre: 7.0,
    ingredients: ['150 g cooked chicken breast (approximately 200 g raw chicken breast)', '100 g cooked baby potatoes (approximately 130 g raw potatoes)', '100 g cucumber, chopped', '100 g cherry tomatoes, halved', '40 g red onion, sliced', '40 g feta cheese, crumbled', '50 g fat-free plain yoghurt', '10 g lemon juice', '2 g garlic powder', '2 g dried oregano', '1 g black pepper', '1 g salt', 'Spray and Cook'],
    method: [],
    source: 'Coached by Vicks — BTC 2026',
  },
  {
    id: 'btc-roast-vegetable-couscous-bowl',
    name: 'Roast Vegetable & Couscous Bowl',
    section: 'lunch',
    kcal: 565.0, p: 50.0, c: 46.0, f: 16.0, fibre: 8.0,
    ingredients: ['150 g cooked chicken breast (approximately 200 g raw chicken breast)', '150 g cooked couscous (approximately 60 g dry couscous)', '200 g mixed roasting vegetables (butternut, baby marrow, red pepper and red', 'onion), chopped', '30 g feta cheese, crumbled', '10 g balsamic glaze', '1 g dried mixed herbs', '1 g salt', '1 g black pepper', 'Spray and Cook'],
    method: [],
    source: 'Coached by Vicks — BTC 2026',
  },
  {
    id: 'btc-lemon-herb-chicken-baby-potatoes-broccol',
    name: 'Lemon Herb Chicken, Baby Potatoes & Broccoli',
    section: 'dinner',
    kcal: 488.0, p: 43.0, c: 33.0, f: 16.0, fibre: 8.0,
    ingredients: ['150 g cooked chicken breast (approximately 200 g raw)', '180 g baby potatoes', '150 g broccoli florets', '5 ml (1 tsp) olive oil', 'Juice of ½ lemon', '1 garlic clove, minced', '1 tsp mixed Italian herbs', 'Salt & black pepper'],
    method: ['Preheat the oven or air fryer to 200°C.', 'Cut the baby potatoes in half and toss with the olive oil, salt and pepper.', 'Roast or air fry for 20–25 minutes, shaking halfway through.', 'Season the chicken with garlic, herbs, salt, pepper and lemon juice.', 'Pan-fry over medium heat for 5–6 minutes per side, or air fry for 12–14 minutes, until the internal temperature reaches 75°C.', 'Allow the chicken to rest for 5 minutes before slicing. You should have approximately 150 g cooked chicken.', 'Steam the broccoli for 4–5 minutes until tender but still bright green.', 'Serve the sliced chicken with the roasted potatoes and broccoli. Finish with extra lemon juice if desired.'],
    source: 'Coached by Vicks — BTC 2026',
  },
  {
    id: 'btc-lean-beef-chilli-with-brown-rice',
    name: 'Lean Beef Chilli with Brown Rice',
    section: 'dinner',
    kcal: 528.0, p: 41.0, c: 41.0, f: 18.0, fibre: 11.0,
    ingredients: ['150 g cooked extra lean beef mince (5% fat) (approximately 190–', '200 g raw)', '100 g cooked brown rice', '100 g canned kidney beans, drained and rinsed', '150 g chopped tomatoes', '50 g onion, finely diced', '1 garlic clove, minced', '1 tsp olive oil (5 ml)', '1 tsp paprika', '½ tsp ground cumin', '½ tsp dried oregano', '½ tsp chilli powder (adjust to taste)', 'Salt & black pepper', 'Fresh coriander (optional)'],
    method: ['Cook the brown rice according to the packet instructions.', 'Sauté the onion and garlic in olive oil until softened.', 'Add the beef mince and cook until browned.', 'Stir in the spices, tomatoes and kidney beans.', 'Simmer for 10–12 minutes, then season to taste.', 'Serve over the brown rice.'],
    source: 'Coached by Vicks — BTC 2026',
  },
  {
    id: 'btc-air-fryer-hake-sweet-potato-green-beans',
    name: 'Air Fryer Hake, Sweet Potato & Green Beans',
    section: 'dinner',
    kcal: 465.0, p: 39.0, c: 36.0, f: 13.0, fibre: 9.0,
    ingredients: ['180 g cooked hake fillet (approximately 230–250 g raw)', '180 g sweet potato, cubed', '150 g green beans, trimmed', '1 tsp olive oil (5 ml)', '½ tsp lemon pepper seasoning', '½ tsp garlic powder', 'Juice of ½ lemon', 'Salt & black pepper'],
    method: ['Toss the sweet potato with the olive oil and roast or air fry at 200°C for 20–25 minutes.', 'Season the hake with lemon pepper, garlic powder, salt and pepper, then air fry for 10–12 minutes until cooked through.', 'Steam the green beans for 4–5 minutes until tender-crisp.', 'Serve with a squeeze of fresh lemon juice.'],
    source: 'Coached by Vicks — BTC 2026',
  },
  {
    id: 'btc-chicken-fajita-couscous-bowl',
    name: 'Chicken Fajita Couscous Bowl',
    section: 'dinner',
    kcal: 489.0, p: 45.0, c: 29.0, f: 18.0, fibre: 7.0,
    ingredients: ['150 g cooked chicken breast (approximately 200 g raw)', '75 g cooked couscous', '100 g mixed peppers, sliced', '50 g red onion, sliced', '20 g light cheddar cheese, grated', '30 g salsa', '1 tsp olive oil (5 ml)', '1 tsp fajita seasoning', 'Salt & black pepper', 'Fresh coriander and lime wedge (optional)'],
    method: ['Prepare the couscous according to the packet instructions.', 'Heat the olive oil and cook the peppers and onion for 5–6 minutes.', 'Add the chicken and fajita seasoning, cooking until heated through.', 'Layer the couscous, chicken mixture, cheese and salsa in a bowl.', 'Garnish with coriander and a squeeze of lime before serving.'],
    source: 'Coached by Vicks — BTC 2026',
  },
  {
    id: 'btc-chicken-meatballs-with-wholewheat-pasta',
    name: 'Chicken Meatballs with Wholewheat Pasta',
    section: 'dinner',
    kcal: 548.0, p: 44.0, c: 45.0, f: 17.0, fibre: 9.0,
    ingredients: ['160 g cooked chicken mince meatballs (approximately 200 g raw', 'chicken mince)', '75 g cooked wholewheat pasta', '150 g tomato puree', '10 g parmesan cheese, grated', '1 garlic clove, minced', '½ tsp dried oregano', '½ tsp Italian herbs', '1 tsp olive oil (5 ml)', 'Salt & black pepper', 'Fresh basil (optional)'],
    method: ['Mix chicken mince with garlic, herbs, salt and pepper, then shape into meatballs.', 'Pan-fry meatballs in olive oil until browned and cooked through.', 'Heat tomato puree with herbs, then add meatballs and simmer for 10 minutes.', 'Cook pasta, then serve topped with meatballs, sauce and parmesan.'],
    source: 'Coached by Vicks — BTC 2026',
  },
  {
    id: 'btc-beef-burger-with-sweet-potato-fries-slaw',
    name: 'Beef Burger with Sweet Potato Fries & Slaw',
    section: 'dinner',
    kcal: 570.0, p: 43.0, c: 44.0, f: 23.0, fibre: 9.0,
    ingredients: ['150 g cooked lean beef burger patty (5% fat mince) (≈180–200 g', 'raw mince)', '1 wholewheat burger roll (±70 g)', '20 g light cheddar cheese', 'Lettuce leaves', '2–3 tomato slices', 'Pickles (optional)', '10 g Nola Lite mayonnaise', '150 g Woolworths frozen sweet potato fries', '80 g cabbage & carrot slaw mix', '30 g plain low-fat yoghurt', '1 tsp lemon juice', 'Salt & pepper'],
    method: ['Cook the beef patty in a pan, grill or air fryer until cooked through.', 'Cook the Woolworths sweet potato fries according to the packet instructions.', 'Mix slaw ingredients together.', 'Assemble burger with cheese, lettuce, tomato and Nola Lite. Serve with fries and slaw.'],
    source: 'Coached by Vicks — BTC 2026',
  },
]
